package scalads
package core

import scalads.writers.Writer


/**
 * @author Bryce Anderson
 *         Created on 5/28/13
 */

/** Will be mixed in with the results returned from queries to facilitate updates
  *
  * Naming is ugly so as to not interfere with an entities natural fields/methods
  */

trait EntityBacker[U, E] { self: U =>

  def ds_serialize(obj: U, writer: Writer[_]): Writer[_]  // Typically generated by the macro

  def ds: Datastore[_, E]

  def transformer: Transformer[U, E]

  def ds_entity: E

  def ds_idString() = transformer.getKeyString(ds_entity)

  def ds_update(): Unit = {
    ds_serialize(self, transformer.newWriter(ds_entity))
    ds.put(self)
  }

  def ds_updateWith(obj: U): Unit = {
    val writer = transformer.newWriter(ds_entity)
    ds_serialize(obj, writer)
    ds.putEntity(writer.result)
  }

  def ds_map(f: U => U): Unit = { ds_updateWith(f(self)) }

  def ds_delete(): Unit = { ds.delete(self) }

}
