package scalads
package core

import scalads.writers.Writer
import com.sun.corba.se.impl.orbutil.ObjectWriter


/**
 * @author Bryce Anderson
 *         Created on 5/28/13
 */

/** Will be mixed in with the results returned from queries to facilitate updates
  *
  * Naming is ugly so as to not interfere with an entities natural fields/methods
  */

trait EntityBacker[U, E] { self: U =>
  def ds_serialize(obj: U, writer: Writer[_]): Unit  // Typically generated by the macro

  def ds: AbstractDatastore[E]

  def ds_entity: E

  private[scalads] def makeWriter(entity: E): Writer[E]

  def ds_updateEntity = ds_serialize(self, makeWriter(ds_entity))

  def put() = { ds_updateEntity; ds.put(self) }

}
