package scalads.core

import scalads._
import com.google.appengine.api.datastore.{Entity, Key}

/**
 * @author Bryce Anderson
 *         Created on 6/9/13
 */
trait GAEEntityBacker[U] extends EntityBacker[U] { self: U =>

  def ds_backingEntity: Entity                    // Typically generated by the macro

  def ds_key = ds_backingEntity.getKey

  def ds_id = ds_key.getId

  def ds_parent: Key = ds_key.getParent()

  def ds_setProperty(name: String, value: Any) = ds_backingEntity.setProperty(name, value)

}
